version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mjjs
      MYSQL_USER: mjjsuser
      MYSQL_PASSWORD: mjjspassword
    volumes:
      - ./DBdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: mjjsuser
      MYSQL_PASSWORD: mjjspassword
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
